config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }

  root to: 'visitors#index'

  get '/playlists/:playlist_id/songs/search', to: 'songs#search'

  get '/playlists/find', to: 'playlists#find'

  get '/playlists/image_search', to: 'playlists#image_search'

  resources :playlists do
    resources :locations
    resources :songs
  end

  devise_scope :user do
    get "/users/:id", to: 'users/registrations#show'
    patch '/users/:id', to: 'users/registrations#update'
  end

end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :playlists
  has_many :users, through: :playlists


end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index

  end

  def new

    render 'new'

  end

  def show
    client = Soundcloud.new({
      :client_id     => "bb3b960126fc0ee3ec16de768439927f",
      :client_secret => "7d39770bb6a7a580e69658cfef542d3b"
    })
    @groove_song = Song.find(params[:id])
    @groove_url = @groove_song.link
  end

  def create
    song = Song.new(title: params[:song_name], artist: params[:song_artist], link: params[:song_id], playlist_id: params[:playlist_id], coverart: params[:coverart])
    if song.coverart != nil
      song.save
    else
      song.coverart = "http://static7.depositphotos.com/1001655/707/v/950/depositphotos_7070089-Woman-with-music-notes.jpg"
      song.save
    end
    @playlist = Playlist.find(song.playlist_id)
    render "playlists/show/"
  end

  def destroy
    playlist = Playlist.find(params[:playlist_id])
    song = playlist.songs.find(params[:id])
    song.destroy

    redirect_to playlist
  end

  def update

  end

  def search

    client = Soundcloud.new({
      :client_id     => "bb3b960126fc0ee3ec16de768439927f",
      :client_secret => "7d39770bb6a7a580e69658cfef542d3b"
    })
    @playlist = Playlist.find(params[:playlist_id])
    @artist_search_results = client.get('/tracks', q: params[:songs][:title])
    render 'search'
  end

end

app/views/songs/_mini_groove_song_card.html.erb
<div class="songcard">
	<a href=<%= url %> class='song'>	
		<div class="coverart">
			<% unless coverart == '' %>
				<img src=<%= coverart %> />
			<%end%>
	</div>
		<div class="songinfo">
			<div id=<%= url %> class="title"><%= title.truncate(60) %></div>
		</div>
	</a>

	<% if session[:user_id] == user.id %>
	<%= link_to [@playlist, track], method: :delete, :class => "icon", data: { confirm: "Are you sure?" } do %>
		<svg xmlns="http://www.w3.org/2000/svg" version="1.0" width="300.000000pt" height="300.000000pt" viewBox="0 0 300.000000 300.000000" preserveAspectRatio="xMidYMid meet">
			<g transform="translate(0.000000,300.000000) scale(0.100000,-0.100000)" fill="#000000" stroke="none">
			<path d="M1434 2576 c-93 -43 -124 -108 -124 -257 0 -90 2 -99 22 -113 12 -9 38 -16 58 -16 20 0 46 7 58 16 20 14 22 23 22 105 0 128 2 129 173 129 177 0 177 0 177 -125 0 -86 2 -95 22 -109 28 -20 97 -20 123 0 18 13 20 26 19 122 0 123 -13 161 -74 216 -53 48 -92 56 -270 56 -142 0 -159 -2 -206 -24z"/>
			<path d="M1131 2499 c-215 -58 -351 -153 -386 -272 -33 -112 -12 -253 50 -327 19 -23 35 -50 35 -61 0 -10 27 -283 60 -606 67 -652 65 -641 145 -711 118 -104 336 -162 607 -162 287 0 515 62 626 169 78 76 64 -7 171 1038 l30 292 35 46 c49 64 59 105 54 226 -5 119 -16 148 -83 214 -70 68 -239 144 -377 170 l-36 7 14 -53 c8 -29 14 -63 14 -75 0 -19 11 -25 72 -44 163 -49 258 -120 258 -192 0 -68 -131 -155 -295 -197 -293 -74 -707 -72 -975 6 -102 29 -212 85 -245 125 -36 43 -34 97 6 143 35 40 143 95 235 121 l62 17 5 51 c3 28 8 61 12 74 9 27 4 27 -94 1z m31 -799 c14 -10 30 -32 37 -47 11 -27 101 -868 101 -943 0 -44 -19 -63 -61 -62 -31 1 -63 22 -79 53 -5 9 -32 233 -60 498 -37 355 -48 487 -40 501 14 26 69 26 102 0z m1073 4 c12 -12 14 -27 10 -58 -3 -22 -23 -216 -45 -431 -22 -214 -44 -419 -49 -454 -12 -77 -40 -112 -90 -113 -45 -1 -65 22 -63 73 4 99 94 924 102 940 28 52 102 75 135 43z m-533 -81 c17 -15 18 -44 18 -511 0 -447 -2 -497 -17 -514 -23 -26 -87 -24 -113 4 -20 21 -20 32 -20 510 0 475 1 489 20 508 25 25 86 27 112 3z"/>
			</g>
			</svg>
	<% end %>
	<% end %>
</div>

app/views/songs/new.html.erb
<div class="new_song">
	<%= form_for :songs, url: {action: 'search'}, html: {method: 'get', :id => 'search-songs'} do |f| %>
		<%= f.text_field :title, placeholder: "Search for Music" %><br><br>
		<%= f.submit "Search" 				%>
	<% end %>
</div>

app/views/songs/search.html.erb
<div class="search_songs">

	<%= form_for :songs, url: {action: 'search'}, html: {method: 'get', :id => 'search-songs'} do |f| %>
		<%= f.text_field :title, :placeholder => "Find a song" %>
		<%= f.submit "Search" %>

	<% end %>
</div>

<% @artist_search_results.each do |song| %>
	<% if song.streamable %>
	<%= link_to playlist_songs_path(@playlist, song_id: song.id, song_name: song.title, song_artist: 'placeholder', coverart: song.artwork_url), :class => 'add-song' do %>
		<%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
		<div class='song-cards'>
			<% unless song.artwork_url == nil %>
				<img class="th searchart" src="<%= song.artwork_url %>" />
			<% else %>
				<img class="th searchart" src="http://static7.depositphotos.com/1001655/707/v/950/depositphotos_7070089-Woman-with-music-notes.jpg" />
			<%end%>

			<p>&nbsp&nbsp<%= truncate(song.title, :length => 50)  %></p>
		</div>
	<%end%>
	<% end %>
<%end%>

app/views/songs/show.html.erb
<%= render partial: 'songs/mini_groove_song_card', locals: {title: @groove_song.title, url: @groove_url, coverart: song.coverart}%>