config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }

  root to: 'visitors#index'

  get '/playlists/:playlist_id/songs/search', to: 'songs#search'

  get '/playlists/find', to: 'playlists#find'

  get '/playlists/image_search', to: 'playlists#image_search'

  resources :playlists do
    resources :locations
    resources :songs
  end

  devise_scope :user do
    get "/users/:id", to: 'users/registrations#show'
    patch '/users/:id', to: 'users/registrations#update'
  end

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  has_many :songs

  has_many :taggings, dependent: :delete_all
  has_many :locations, through: :taggings

  validates :title, presence: true
end
	

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  respond_to :html, :js, :xml, :json
  GOOGLE_API_KEY = 'AIzaSyAxtw4-zu7vqxoUxtk4e7QTz7nvLZOOLVY'
  GOOGLE_SEARCH_CX = '010444673571637133719:ltyfqnzcrmy'

  def index

  end

  def new
    @playlist = Playlist.new

    render :new
  end
 
  def show
    @playlist = Playlist.find(params[:id])
    @client = Soundcloud.new({
      :client_id     => "bb3b960126fc0ee3ec16de768439927f",
      :client_secret => "7d39770bb6a7a580e69658cfef542d3b"
    }) 
    @picture = @playlist.art_url
    unless @picture
      @picture = "http://1.bp.blogspot.com/-NFIeRN1TNpU/Ukou19njwHI/AAAAAAAAARQ/iypdhkQVZvI/s200/7313935-heavy-metal-rock-and-roll-devil-horns-hand-sign-with-a-black-leather-studded-bracelet.jpg"
    end

    render 'show'



  end

  def create
    @playlist = Playlist.new(title: params[:playlist][:title], user_id: current_user.id, art_url: params[:playlist][:art_url])

    if @playlist.save
      render 'show'
    else
      render :new
    end
  end

  def destroy
    playlist = current_user.playlists.find(params[:id])
    playlist.destroy

    redirect_to '/'
  end

  def update

  end

  def find
    @current_users_around = current_users_around
  end

  def image_search
    @title = params[:playlists][:title]
    if params[:playlists][:q]
      @query = params[:playlists][:q]
      page = params[:playlists][:page] || 1
      @results = GoogleCustomSearchApi.search(params[:playlists][:q], {page: page, searchtype: 'image'})
      
    end
    render 'image_search'
  end

end

app/views/playlists/find.html.erb
<div class="welcome">
<p class="welcome view"> Playlists nearby </p>
<div class="playlist_find">

  <% if @current_users_around.empty? %>
    <p class="welcome">No users currently. Please try again later</p>
  <% end %>

  <% @current_users_around.each do |u| %>
    <% @playlist = u.playlists.last %>
      <% if @playlist %>
        <div class="playlists">
          <%= link_to playlist_path(@playlist), class: 'playlists-around' do %>
            <div class="cover" style="background-image: url(<%=@playlist.art_url%>);"></div>

          <% end %>
        </div>
      <% end %>
  <% end %>
</div>
</div>

app/views/playlists/image_search.html.erb
  <% if @results && !@results.items.empty? %>
    <div class='image-results'>
      <% @results.items.each do |item| %>
            <% if item['pagemap'] &&
                  item['pagemap']['cse_thumbnail'] &&
                  img = item.pagemap.cse_thumbnail.first %>
              <%=link_to playlists_path(playlist: {title: @title, art_url: img.src}), :class => 'new_playlists' do %>
	              <div class='cover' style="background-image: url(<%=img.src%>)"></div>
              <% end %>
            <% end %>
      <% end %>
    </div>
    <div class='search-prev-next'>
      <div class='row text-center'>
        <% if @results.previous_page %>
          <%= link_to '<< Previous',
            playlists_image_search_path(playlists: {q: @query, page: @results.previous_page, title: @title}),
            class: 'btn' %>
        <% end %>
        <% @results.pages.times do |i| %>
          <%= link_to i + 1,
            playlists_image_search_path(playlists: {q: @query, page: i+1, title: @title}),
            class: 'btn btn-page' %>
        <% end %>
        <% if @results.next_page %>
          <%= link_to 'Next >>',
            playlists_image_search_path(playlists: {q: @query,
                                    page: @results.next_page, title: @title}),
            class: 'btn' %>
        <% end %>
      </div>
    </div>
  <% else %>
    <h4>No results</h4>
  <% end %>

app/views/playlists/new.html.erb
<% if @playlist %>
  <% @playlist.errors.full_messages.each do |error_msg| %>
    <ul>
    <li><%= error_msg %></li>
	  </ul>
  <% end %>
<% end %>

<%= form_for :playlists, url: {action: 'image_search'}, html: {method: 'GET', :id => 'image_search', :class => 'new_playlist'} do |f| %>
	<%= f.text_field :title, :placeholder => 'Title' %>
	<%= f.text_field :q, :placeholder => 'Search Cover Art' %>
	<%= f.submit 'Search' %>
<% end %>

app/views/playlists/show.html.erb
<div class="now_playing">

	<p class="welcome"><%= @playlist.title %></p>


	<div class="cover-large" style="background-image:url(<%= @playlist.art_url %>)"></div>
	<div class='playlistButtons'>
  <a id='playPlaylist' href="">Play</a>
  <%= link_to 'Delete Playlist', playlist_path(@playlist),
          method: :delete,
          data: { confirm: "Are you sure?" }, :class => "delete"%>

  <%= link_to "Tag Location", new_playlist_location_path(@playlist), :class => "tag" %>
  </div>


</div>
<% if current_user == @playlist.user %>
<div id='<%= @playlist.id %>' class="playlist_locations current_user">
<% else %>
<div id='<%= @playlist.id %>' class="playlist_locations">
<% end %>

	<% @playlist.taggings.each do |tag| %> 
		<li><%= link_to tag.location.name, playlist_location_path(tag.playlist, tag.location) %></li>
	<% end %>
</div>


<br />

<div class="userPlaylist">

	<div id="playlist">

		<% @playlist.songs.each do |song| %>
			<%= render partial: 'songs/mini_groove_song_card', locals: {user: @playlist.user, track: song, title: song.title, url: song.link, coverart: song.coverart}%>
		<% end %>
	</div>


</div>