config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }

  root to: 'visitors#index'

  get '/playlists/:playlist_id/songs/search', to: 'songs#search'

  get '/playlists/find', to: 'playlists#find'

  get '/playlists/image_search', to: 'playlists#image_search'

  resources :playlists do
    resources :locations
    resources :songs
  end

  devise_scope :user do
    get "/users/:id", to: 'users/registrations#show'
    patch '/users/:id', to: 'users/registrations#update'
  end

end

app/views/layouts/_navigation.html.erb
<div class="nav-bar">
	<div class="nav-bar-left">
		<div id='menu'>
			<svg xmlns="http://www.w3.org/2000/svg" version="1.0" width="300.000000pt" height="300.000000pt" viewBox="0 0 300.000000 300.000000" preserveAspectRatio="xMidYMid meet">
				<g transform="translate(0.000000,300.000000) scale(0.100000,-0.100000)" fill="#D9D9D9" stroke="none">
					<path d="M328 2430 c-45 -14 -83 -41 -108 -78 -20 -29 -25 -48 -25 -102 0 -79 26 -125 90 -162 l40 -23 1165 -3 1164 -2 51 25 c73 36 100 81 100 165 0 84 -27 129 -99 165 l-50 25 -1150 -1 c-633 0 -1163 -4 -1178 -9z"/>
					<path d="M328 1680 c-45 -14 -83 -41 -108 -78 -20 -29 -25 -48 -25 -102 0 -84 27 -129 99 -165 l50 -25 1156 0 1156 0 50 25 c72 36 99 81 99 165 0 84 -27 129 -99 165 l-50 25 -1150 -1 c-633 0 -1163 -4 -1178 -9z"/>
					<path d="M294 915 c-72 -36 -99 -81 -99 -165 0 -84 27 -129 99 -165 l50 -25 1156 0 1156 0 50 25 c72 36 99 81 99 165 0 84 -27 129 -99 165 l-50 25 -1156 0 -1156 0 -50 -25z"/>
				</g>
			</svg>
		</div>
		<ul class="neste">
			<li>
				<%= link_to 'Home', root_path, :id => 'home' %>
			</li>

<% if user_signed_in? %>

				<li>
					<%= link_to 'Edit Profile', edit_user_registration_path, :id => 'user' %>
				</li>
				<li>
					<%= link_to "Find Playlists", playlists_find_path, :id => 'find-playlist' %>
				</li>
				<li>
					<%= link_to "New Playlist", new_playlist_path, :id => 'new-playlist'  %>
				</li>
				<li>
					<%= link_to 'Exit', destroy_user_session_path, :method=>'delete', :id => 'signout' %>
				</li>
			</ul>
		</div>
		<div class="nav-bar-right">
	    <a id="new-playlists" href="/playlists">
			<svg xmlns="http://www.w3.org/2000/svg" version="1.0" width="300.000000pt" height="300.000000pt" viewBox="0 0 300.000000 300.000000" preserveAspectRatio="xMidYMid meet">
				<g transform="translate(0.000000,300.000000) scale(0.100000,-0.100000)" fill="#D9D9D9" stroke="none">
				<path d="M1435 2986 c-40 -17 -82 -67 -95 -114 -6 -23 -10 -250 -10 -619 l0 -583 -582 0 c-395 0 -596 -4 -623 -11 -52 -15 -111 -74 -120 -122 -17 -87 36 -173 120 -196 27 -7 228 -11 623 -11 l582 0 0 -582 c0 -395 4 -596 11 -623 15 -52 74 -111 122 -120 87 -17 173 36 196 120 7 27 11 228 11 623 l0 582 583 0 c394 0 595 4 622 11 84 23 137 109 120 196 -9 48 -68 107 -120 122 -27 7 -228 11 -622 11 l-583 0 0 583 c0 369 -4 596 -10 619 -28 100 -134 154 -225 114z"/>
				</g>
				</svg>
			</a>
		</div>
	<% else %>
		<li>
			<%= link_to 'Login', new_user_session_path, :id => 'signin' %>
		</li>
		<li>
			<%= link_to 'Join', new_user_registration_path, :id => 'signup' %>
		</li>
		</ul>
		</div>
	<% end %>
						<div class="nav-bar-center">
							<svg xmlns="http://www.w3.org/2000/svg" version="1.0" width="300.000000pt" height="300.000000pt" viewBox="0 0 300.000000 300.000000" preserveAspectRatio="xMidYMid meet">
								<g transform="translate(0.000000,300.000000) scale(0.100000,-0.100000)" fill="#D9D9D9" stroke="none">
								<path d="M1370 2663 c-217 -34 -409 -131 -566 -288 -104 -103 -159 -180 -220 -309 -79 -168 -86 -211 -91 -538 -5 -285 -4 -287 17 -298 17 -9 26 -8 45 4 l23 15 4 268 c4 236 7 277 26 348 93 341 365 610 699 692 104 25 295 23 403 -5 261 -69 489 -259 610 -507 81 -167 92 -228 97 -520 2 -137 6 -260 8 -272 6 -27 37 -38 65 -23 19 10 20 19 20 263 0 207 -4 268 -19 342 -100 484 -525 839 -996 834 -55 -1 -111 -3 -125 -6z"/>
								<path d="M580 1150 c-20 -5 -47 -22 -62 -41 l-28 -33 0 -329 c0 -360 2 -372 60 -402 23 -12 67 -15 205 -15 l175 0 38 34 37 34 3 326 c3 362 1 374 -61 411 -27 17 -53 20 -182 22 -82 1 -166 -2 -185 -7z m328 -102 c17 -17 17 -599 0 -616 -17 -17 -299 -17 -316 0 -9 9 -12 92 -12 313 0 166 3 305 7 308 12 13 308 8 321 -5z"/>
								<path d="M2089 1151 c-99 -32 -99 -31 -99 -411 0 -430 -13 -410 260 -410 189 0 218 7 245 60 22 42 22 657 1 699 -30 58 -56 65 -226 68 -85 1 -167 -1 -181 -6z m319 -103 c17 -17 17 -599 0 -616 -17 -17 -299 -17 -316 0 -17 17 -17 599 0 616 17 17 299 17 316 0z"/>
								<path d="M336 964 c-12 -31 -7 -459 6 -472 15 -15 51 -15 66 0 17 17 17 459 0 476 -17 17 -65 15 -72 -4z"/>
								<path d="M2592 968 c-17 -17 -17 -459 0 -476 15 -15 51 -15 66 0 9 9 12 76 12 238 0 237 -2 250 -45 250 -12 0 -26 -5 -33 -12z"/>
								</g>
								</svg>
						</div>
				</div>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html lang="en">
<head>
  <title>Audioscape</title>
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />




  <script src="//cdn.jsdelivr.net/rsvp/3.0.6/rsvp.min.js"></script>
  <!-- Firebase -->
  <script src="https://cdn.firebase.com/js/client/2.0.2/firebase.js"></script>

  <!-- GeoFire -->
  <script src="https://cdn.firebase.com/libs/geofire/3.2.1/geofire.min.js"></script>

  <script src="https://connect.soundcloud.com/sdk/sdk-3.0.0.js"></script>
  <script type="text/javascript">
    SC.initialize({
      clientId: "b6d05ac1306c6dda3e9b9b124aab1171"
    });
  </script>
<link href='https://fonts.googleapis.com/css?family=Skranji' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Ruda:900' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag 'application'%>


  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <div id='user<%=current_user.id%>' style='display:none'></div>
  <%end%>

  <header>
    <%= render 'layouts/navigation' %>
  </header>

  <div class="container">
    <%= yield %>
  </div>

<% if current_user %>
  <div id="tracks"></div>

  <footer>
    <audio style='display:none'></audio>
    <div id='secret-playlist' style='display:none'></div>
    <div id="music">

    <div id="current">
      <h6><span></span></h6>
    </div>
    <!-- <a id="last" href=""> -->
      <svg id='last' class='last' xmlns="http://www.w3.org/2000/svg" version="1.0" width="300.000000pt" height="300.000000pt" viewBox="0 0 300.000000 300.000000" preserveAspectRatio="xMidYMid meet">
      <g transform="translate(0.000000,300.000000) scale(0.100000,-0.100000)" fill="#00B4CC">
      <path d="M2410 2513 l-585 -484 -3 481 c-1 282 -6 480 -11 478 -8 -3 -443 -360 -1449 -1192 -199 -165 -359 -303 -355 -307 5 -3 276 -226 603 -495 327 -268 729 -599 893 -734 164 -135 302 -246 308 -248 5 -2 9 179 9 472 0 262 3 476 8 476 4 -1 268 -216 587 -479 l580 -477 3 748 c1 411 1 1085 0 1496 l-3 748 -585 -483z"/>
      </g>
      </svg>
    <!-- </a> -->
    <!-- <a id="play"> -->
      <svg id='play' class='play' xmlns="http://www.w3.org/2000/svg" version="1.0" width="300.000000pt" height="300.000000pt" viewBox="0 0 300.000000 300.000000" preserveAspectRatio="xMidYMid meet">
        <g transform="translate(0.000000,300.000000) scale(0.100000,-0.100000)" fill="#00B4CC">
        <path d="M309 2983 c-20 -23 -26 -2915 -6 -2953 9 -18 21 -25 42 -25 22 0 243 134 815 495 432 271 954 600 1160 729 l375 236 0 35 0 35 -895 562 c-1416 891 -1436 903 -1457 903 -11 0 -27 -7 -34 -17z"/>
        </g>
      </svg>
    <!-- </a> -->
    <!-- <a id="pause" href=""> -->
      <svg id='pause' class='pause' xmlns="http://www.w3.org/2000/svg" version="1.0" width="300.000000pt" height="374.000000pt" viewBox="0 0 300.000000 374.000000" preserveAspectRatio="xMidYMid meet">
        <g transform="translate(0.000000,374.000000) scale(0.100000,-0.100000)" fill="#00B4CC">
        <path d="M583 3385 c-126 -28 -205 -93 -232 -190 -8 -28 -11 -418 -11 -1326 0 -1426 -3 -1352 65 -1422 20 -21 54 -46 77 -58 126 -64 381 -64 508 1 50 26 84 60 114 115 l21 40 3 1295 c2 858 -1 1311 -8 1343 -19 91 -89 160 -194 193 -72 22 -264 27 -343 9z"/>
        <path d="M2114 3385 c-109 -24 -181 -73 -220 -152 -18 -37 -19 -82 -19 -1363 l0 -1325 21 -40 c30 -55 64 -89 114 -115 127 -65 382 -65 508 -1 23 12 57 37 77 58 68 70 65 -4 65 1422 0 908 -3 1298 -11 1326 -28 99 -107 163 -236 190 -84 18 -217 18 -299 0z"/>
        </g>
      </svg>
    <!-- </a> -->
    <!-- <a id="next" href=""> -->
      <svg id='next' class='next' xmlns="http://www.w3.org/2000/svg" version="1.0" width="300.000000pt" height="300.000000pt" viewBox="0 0 300.000000 300.000000" preserveAspectRatio="xMidYMid meet">
        <g transform="translate(0.000000,300.000000) scale(0.100000,-0.100000)" fill="#00B4CC">
        <path d="M0 1500 l0 -1500 343 283 c188 156 452 374 587 485 l245 203 3 -481 c1 -280 6 -480 11 -478 9 3 1430 1174 1769 1458 l42 35 -597 490 c-328 270 -734 603 -901 740 -167 138 -308 252 -313 253 -5 2 -9 -182 -9 -473 0 -288 -4 -475 -9 -473 -5 2 -157 125 -338 273 -180 149 -442 363 -580 478 l-253 207 0 -1500z"/>
        </g>
      </svg>
    <!-- </a> -->
    <!-- <a id='viewPlaylist' href=""> -->
      <svg id='viewPlaylist' class='viewPlaylist' xmlns="http://www.w3.org/2000/svg" version="1.0" width="300.000000pt" height="300.000000pt" viewBox="0 0 300.000000 300.000000" preserveAspectRatio="xMidYMid meet">
        <g transform="translate(0.000000,300.000000) scale(0.100000,-0.100000)" fill="#D9D9D9">
          <path d="M328 2430 c-45 -14 -83 -41 -108 -78 -20 -29 -25 -48 -25 -102 0 -79 26 -125 90 -162 l40 -23 1165 -3 1164 -2 51 25 c73 36 100 81 100 165 0 84 -27 129 -99 165 l-50 25 -1150 -1 c-633 0 -1163 -4 -1178 -9z"/>
          <path d="M328 1680 c-45 -14 -83 -41 -108 -78 -20 -29 -25 -48 -25 -102 0 -84 27 -129 99 -165 l50 -25 1156 0 1156 0 50 25 c72 36 99 81 99 165 0 84 -27 129 -99 165 l-50 25 -1150 -1 c-633 0 -1163 -4 -1178 -9z"/>
          <path d="M294 915 c-72 -36 -99 -81 -99 -165 0 -84 27 -129 99 -165 l50 -25 1156 0 1156 0 50 25 c72 36 99 81 99 165 0 84 -27 129 -99 165 l-50 25 -1156 0 -1156 0 -50 -25z"/>
        </g>
      </svg>
    <!-- </a> -->
    <!-- <a id='shuffle' href=""> -->
      <svg id='shuffle' class='shuffle' xmlns="http://www.w3.org/2000/svg" version="1.0" width="300.000000pt" height="300.000000pt" viewBox="0 0 300.000000 300.000000" preserveAspectRatio="xMidYMid meet">
        <g transform="translate(0.000000,300.000000) scale(0.100000,-0.100000)" fill="#00B4CC" stroke="none">
        <path d="M2400 2362 l0 -152 -248 0 c-239 0 -250 -1 -290 -22 -27 -15 -223 -211 -542 -543 -274 -285 -514 -527 -532 -537 -29 -15 -65 -17 -298 -18 -146 0 -281 -5 -300 -10 -20 -5 -51 -26 -70 -45 -33 -34 -35 -41 -35 -101 0 -64 1 -66 42 -105 l42 -39 351 0 c325 0 354 1 388 19 22 11 231 220 517 517 264 274 493 509 508 523 63 58 77 61 279 61 l188 0 0 -150 c0 -84 4 -150 9 -150 5 0 11 4 13 9 2 4 86 79 188 166 102 87 215 185 252 217 l66 60 -246 210 c-136 116 -255 218 -264 226 -17 14 -18 7 -18 -136z m260 -123 c110 -95 200 -175 200 -179 0 -11 -397 -350 -410 -350 -6 0 -10 38 -10 97 0 86 -3 99 -22 120 -21 22 -26 23 -207 23 -235 0 -243 -3 -386 -151 -55 -57 -210 -219 -345 -359 -447 -465 -565 -582 -597 -596 -25 -11 -105 -14 -359 -14 -286 0 -329 2 -354 17 -69 40 -64 153 7 181 17 7 134 12 298 14 250 3 273 5 315 25 49 23 85 59 685 682 262 272 382 390 410 402 35 16 69 19 273 19 l233 0 24 25 c23 22 25 32 25 120 0 58 4 95 10 95 6 0 100 -77 210 -171z"/>
        <path d="M150 2197 c-27 -14 -67 -68 -76 -104 -15 -58 20 -128 79 -161 28 -15 73 -18 343 -22 365 -6 322 9 478 -161 54 -59 113 -115 131 -123 79 -38 172 -7 206 68 23 51 23 71 1 118 -23 50 -315 354 -363 379 -36 18 -61 19 -406 19 -274 0 -374 -3 -393 -13z m767 -38 c30 -11 208 -182 304 -292 51 -58 59 -73 59 -108 0 -51 -13 -75 -50 -94 -71 -37 -108 -17 -241 126 -151 162 -124 153 -489 159 -340 6 -344 6 -377 74 -20 42 -11 79 27 117 l28 29 356 0 c223 0 365 -4 383 -11z"/>
        <path d="M1550 1379 c-44 -27 -57 -44 -70 -92 -20 -70 -1 -100 180 -288 108 -113 178 -178 205 -190 35 -16 69 -19 287 -19 l247 0 3 -153 3 -153 258 221 c142 121 259 223 260 226 1 4 -116 108 -260 233 l-263 226 0 -150 0 -150 -190 0 c-169 0 -195 2 -228 19 -20 11 -89 74 -151 142 -64 68 -129 128 -148 135 -46 20 -93 17 -133 -7z m107 -30 c15 -5 89 -70 163 -143 96 -95 146 -137 175 -147 28 -10 92 -14 217 -14 173 0 177 0 202 24 24 23 26 30 26 117 0 51 3 95 8 98 12 7 415 -340 410 -354 -4 -11 -402 -350 -410 -350 -5 0 -8 45 -8 100 0 94 -2 103 -25 125 l-24 25 -236 0 c-180 0 -243 3 -268 14 -18 8 -103 85 -189 172 -155 157 -195 211 -182 251 14 44 31 67 59 79 37 16 47 17 82 3z"/>
        </g>
      </svg>
    <!-- </a> -->
  </div>
  </footer>
<% end %>




</body>
</html>